### ISSUE TITLE
Migrate hosting

### ISSUE THREAD

**Issue by woodyrew** [metalsmith/metalsmith.io#197]
Following the discussion in [Automated Build/Deploy](#149) #149, it would be good to migrate over to a more appropriate solution.
The following features would be beneficial:
- Static hosting *
- HTTPS (#187)
- Continuous Deployment
- Ability to build for a branch *

\* _Nice to have_

I believe Netlify has all these features available and is free for open source projects. It would be nice to hear of other options and features that we might want to take advantage of.

**Comment by woodyrew** [comment]
This is for discussion only until [the DNS issue](#198) can be resolved.

**Comment by woodyrew** [comment]
This is for discussion only until #198 can be resolved.

**Comment by ismay** [comment]
In #149 a couple of services were mentioned for static hosting (netlify, surge, gh pages). After thinking about it I'd recommend github pages with travis and cloudflare.

Cloudflare for the https (granted, [it's not perfect](https://stirling.co/blog/cloudflare-mitm/), but it works well). Travis for continuous deployment and ability to build to a branch. I've had this exact build setup (build after a push to `development` branch, test, commit build results to `master` after succes, and it's live), and it works just fine.

Reason I'd recommend this over netlify or surge is that these services require separate authentication. I think that the current situation with updating the site arose partially because certain aspects of the site can't be changed from the repo. I think It wouldn't be good to move even more aspects of it outside of this repo. Github pages doesn't require separate authentication, only access to the repo, which seems much more appropriate.

Once dns, cloudflare and travis are set up, they won't require any further attention. We then should be able to handle everything from the repo itself. As before, I'd be happy to help with this. Let me know if I can do anything.

**Comment by ismay** [comment]
Actually, @woodyrew, after having used netlify for a while, I completely agree with your above comment and take back what I said. The features you named are all really well implemented by netlify and supernice to have. I we could move the site to netlify that would be great.

**Comment by woodyrew** [comment]
I'll contact Segment to see if they're prepared for us to do this or if they could set it up for us.

**Comment by ismay** [comment]
In that case it would be nice if they could give us access, or wait with setting it up until the refactor is done, so that we don’t have to ask them to change the build task.

**Comment by f2prateek** [comment]
I think we could close this out now?

**Comment by ismay** [comment]
👍. Migrated to netlify.
