### ISSUE TITLE
DOCS on navbar links to Welcome section

### ISSUE THREAD

**Issue by imchell** [metalsmith/metalsmith.io#335]
Don't know whether this is on purpose or not - DOCS button links to https://metalsmith.io/#welcome while there exists a page for docs (https://metalsmith.io/docs). Besides, Get Started button also directing to https://metalsmith.io/#welcome makes DOCS a little redundant if it actually represents https://metalsmith.io/#welcome.

**Comment by webketje** [comment]
Half a year ago this site was single-page and I've been gradually updating it.
It is meant to redirect to the dedicated docs page in the future, that's one of those works-in-progress, I wasn't even sure anyone would find https://metalsmith.io/docs.
But this particular job is quite time-consuming, because:
- The "old docs" under #welcome must be removed
- New content must fill the homepage (a "featured" slider, a "starters" section)
- The new docs must be on par or better than the old docs. *I haven't had any feedback on this so far, so feel free to add*.

Thank you for the reminder, now this is documented & more visible as a GH issue

**Comment by webketje** [comment]
If you would like to get (slightly) more involved, there is a GH team"discussion board" at https://github.com/orgs/metalsmith/teams/ideators (no strings attached, it's just reading & providing feedback on ideas & plans that aren't ready for publication yet) & ofc always welcome at https://gitter.im/metalsmith/community

I'm open to changing the DOCS link to point to the new docs (hope I get some feedback from there in the coming 2 weeks).
For ex I did a proofread of "Writing plugins" yesterday and saw 5-some spelling mistakes

**Comment by imchell** [comment]
@webketje Sure, I'd like to join the discussion board.

**Comment by webketje** [comment]
Fixed in the meantime
